### ISSUE TITLE
Error make in Linux Mint 18

### ISSUE THREAD

**Issue by luigystoro** [onetransistor/winbootx#1]
Error make in Linux Mint 18

` error: ‘nullptr’ was not declared in this scope`

**Comment by onetransistor** [comment]
`g++` should be called with `-std=gnu++11`. QMake should already add this argument. Are you using Qt5 qmake? What's the output of `qmake --version`?

**Comment by luigystoro** [comment]
qmake --version
QMake version 3.0
Using Qt version 5.5.1 in /usr/lib/x86_64-linux-gnu

**Comment by onetransistor** [comment]
Check this build: https://github.com/onetransistor/winbootx/releases

**Comment by luigystoro** [comment]
Apparently there are problems with some lib

`ldd /opt/winbootx/WinBootX
/opt/winbootx/WinBootX: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by /opt/winbootx/WinBootX)
/opt/winbootx/WinBootX: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5: version `Qt_5' not found (required by /opt/winbootx/WinBootX)
/opt/winbootx/WinBootX: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.6' not found (required by /opt/winbootx/WinBootX)
/opt/winbootx/WinBootX: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5' not found (required by /opt/winbootx/WinBootX)
	linux-vdso.so.1 =>  (0x00007ffcb1b3b000)
	libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007fdc6d9cb000)
	libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007fdc6d33e000)
	libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007fdc6cdf5000)
	libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007fdc6c91f000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdc6c702000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fdc6c37f000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fdc6c169000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdc6bda0000)
	libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007fdc6bb5e000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007fdc6b93c000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fdc6b734000)
	/lib64/ld-linux-x86-64.so.2 (0x000055cc58328000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007fdc6b4e0000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fdc6b1cf000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fdc6ae95000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fdc6ab8b000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007fdc6a966000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007fdc6a708000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fdc6a4ed000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 (0x00007fdc6a27c000)
	libicui18n.so.55 => /usr/lib/x86_64-linux-gnu/libicui18n.so.55 (0x00007fdc69e1a000)
	libicuuc.so.55 => /usr/lib/x86_64-linux-gnu/libicuuc.so.55 (0x00007fdc69a85000)
	libpcre16.so.3 => /usr/lib/x86_64-linux-gnu/libpcre16.so.3 (0x00007fdc6981f000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fdc6961b000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fdc69415000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fdc691a5000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007fdc68f9c000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fdc68d7a000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fdc68acf000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007fdc688aa000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fdc68681000)
	libxcb-dri3.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007fdc6847e000)
	libxcb-present.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-present.so.0 (0x00007fdc6827a000)
	libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007fdc68073000)
	libxshmfence.so.1 => /usr/lib/x86_64-linux-gnu/libxshmfence.so.1 (0x00007fdc67e70000)
	libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007fdc67c41000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fdc67a2f000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007fdc6782c000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007fdc67625000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007fdc67423000)
	libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007fdc6720a000)
	libxcb-dri2.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0 (0x00007fdc67004000)
	libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007fdc66dfe000)
	libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007fdc66bef000)
	libicudata.so.55 => /usr/lib/x86_64-linux-gnu/libicudata.so.55 (0x00007fdc65137000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fdc64f33000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fdc64d2c000)`

**Comment by onetransistor** [comment]
Install `libqt5gui5, libqt5core5a`. Also, if you installed deb with dpkg, run `sudo apt install -f`

Updated release: https://github.com/onetransistor/winbootx/releases/tag/v1.0.0-beta

**Comment by luigystoro** [comment]
install 5.6.1
qmake --version
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory

**Comment by onetransistor** [comment]
It's trying to run Qt4 qmake, which is not compatible with this.

    sudo apt install qt5-qmake qt5-default

should fix that. Since you install 5.6.1, is the binary from the [release](https://github.com/onetransistor/winbootx/releases/tag/v1.0.0-beta) starting?

**Comment by luigystoro** [comment]
the binary not start

**Comment by onetransistor** [comment]
Can you run?

    /usr/lib/x86_64-linux-gnu/qt5/bin/qmake

**Comment by luigystoro** [comment]
I have replaced 'nullptr' with 0 in all classes. With this I was able to compile and executed the tool

I now try to create the bootable usb, but after starting, it asks for confirmation and then does nothing

**Comment by onetransistor** [comment]
Download the latest code, compile it and run with sudo (preferably in a terminal, to see any error output)
